export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_JSON_BODY: "INVALID_JSON_BODY",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_ORGANIZATION_ALREADY_EXISTS: "AUTH_ORGANIZATION_ALREADY_EXISTS",
  AUTH_ACCESS_TOKEN_INVALID: "AUTH_ACCESS_TOKEN_INVALID",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  ORG_MEMBER_NOT_FOUND: "ORG_MEMBER_NOT_FOUND",
  ORG_MEMBER_ALREADY_EXISTS: "ORG_MEMBER_ALREADY_EXISTS",
  ORG_LAST_ADMIN: "ORG_LAST_ADMIN",

  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_FORBIDDEN: "PROJECT_FORBIDDEN",

  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_FORBIDDEN: "TASK_FORBIDDEN",
  TASK_ASSIGNMENT_ALREADY_EXISTS: "TASK_ASSIGNMENT_ALREADY_EXISTS",
  TASK_ASSIGNMENT_NOT_FOUND: "TASK_ASSIGNMENT_NOT_FOUND",
  ASSIGNEE_NOT_IN_ORGANIZATION: "ASSIGNEE_NOT_IN_ORGANIZATION",

  ASSIGNMENT_NOTIFICATION_ENQUEUE_FAILED: "ASSIGNMENT_NOTIFICATION_ENQUEUE_FAILED",

  JOB_NOT_FOUND: "JOB_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
